version: '3'
services:
  nginx:
    container_name: online_exam_nginx
    image: nginx:1.15.7-alpine
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d

  mysql:
    container_name: online_exam_mysql
    image: mysql:8.0.13
    environment:
      MYSQL_DATABASE: online_exam
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    restart: always

  redis:
    image: "redis:alpine"
    hostname: redis
    ports:
      - "6379:6379"

  app:
    restart: always
    build: ./OnlineExam-master
    working_dir: /app
    volumes:
      - ./OnlineExam-master:/app
      - ~/.m2:/root/.m2
    expose:
      - "8081"
    depends_on:
      - nginx
      - mysql
      - redis
    command: mvn clean spring-boot:run -Dspring-boot.run.profiles=docker